pipeline{
	agent any
	
	stages{
		stage('Check stage'){
			steps{
				withMaven(maven : 'Maven'){
					sh 'mnv --version'
				}
			}
		}
		
		stage('Compile stage'){
			steps{
				withMaven(maven : 'Maven'){
					sh 'mvn -f mvn-math/pom.xml clean compile'
				}
			}
		}
		
		stage('Test stage'){
			steps{
				withMaven(maven : 'Maven'){					
					sh 'mvn -f mvn-math/pom.xml test'
				}
			}
		}
	}