pipeline{
	agent any
	
	stages{
		stage('Check stage'){
			steps{
				withMaven(maven : 'Maven'){
					bat 'mnv --version'
				}
			}
		}
		
		stage('Compile stage'){
			steps{
				withMaven(maven : 'Maven'){
					bat 'mvn -f mvn-math/pom.xml compile'
				}
			}
		}
		
		stage('Test stage'){
			steps{
				withMaven(maven : 'Maven'){					
					bat 'mvn -f mvn-math/pom.xml install'
				}
			}
		}
	}}